import { StyleSheet } from 'react-native';
import { COLORS, SCREEN_CONFIG } from '../../../constants/config';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.LIGHT,
  },
  hero: {
    height: 250,
    justifyContent: 'center',
    alignItems: 'center',
  },
  heroImage: {
    opacity: 0.8,
  },
  heroOverlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  heroTitle: {
    fontSize: 28,
    fontWeight: 'bold',
    color: COLORS.WHITE,
    textAlign: 'center',
    marginBottom: 5,
  },
  heroTitleHighlight: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#FFD700',
    textAlign: 'center',
    marginBottom: 10,
  },
  heroSubtitle: {
    fontSize: 16,
    color: COLORS.WHITE,
    textAlign: 'center',
    opacity: 0.9,
  },
  searchCard: {
    backgroundColor: COLORS.WHITE,
    margin: 16,
    padding: 20,
    borderRadius: SCREEN_CONFIG.BORDER_RADIUS,
    ...SCREEN_CONFIG.SHADOW,
  },
  formGroup: {
    marginBottom: 20,
    position: 'relative',
    zIndex: 1,
  },
  label: {
    fontSize: 16,
    fontWeight: '600',
    color: COLORS.DARK,
    marginBottom: 8,
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: COLORS.LIGHT_GRAY,
    borderRadius: SCREEN_CONFIG.BORDER_RADIUS,
    backgroundColor: COLORS.WHITE,
    paddingHorizontal: 12,
    position: 'relative',
    zIndex: 10,
  },
  icon: {
    marginRight: 8,
    pointerEvents: 'none',
  },
  input: {
    flex: 1,
    paddingVertical: 12,
    fontSize: 16,
    color: COLORS.DARK,
    outlineStyle: 'none',
  },
  placeholderText: {
    color: COLORS.GRAY,
  },
  // Autocomplete suggestions dropdown
  suggestions: {
    position: 'absolute',
    top: 80,
    left: 0,
    right: 0,
    backgroundColor: '#FFFFFF',
    borderWidth: 2,
    borderColor: '#E2E8F0',
    borderRadius: 12,
    maxHeight: 220,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 16,
    elevation: 10,
    zIndex: 1000,
  },
  suggestionItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
    gap: 10,
  },
  suggestionText: {
    fontSize: 15,
    color: '#334155',
    fontWeight: '500',
  },
  popularContainer: {
    marginTop: 8,
  },
  popularLabel: {
    fontSize: 14,
    color: COLORS.GRAY,
    marginBottom: 6,
  },
  popularTags: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  popularTag: {
    backgroundColor: '#E3F2FD',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    marginRight: 8,
    marginBottom: 6,
  },
  popularTagText: {
    fontSize: 12,
    color: '#1976D2',
    fontWeight: '500',
  },
  dateRow: {
    flexDirection: 'row',
    marginBottom: 20,
  },
  picker: {
    flex: 1,
    height: 50,
  },
  priceRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  priceInput: {
    flex: 1,
    textAlign: 'center',
  },
  priceSeparator: {
    marginHorizontal: 8,
    fontSize: 16,
    color: COLORS.GRAY,
  },
  searchButton: {
    backgroundColor: COLORS.PRIMARY,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 16,
    borderRadius: SCREEN_CONFIG.BORDER_RADIUS,
    marginTop: 10,
  },
  searchButtonDisabled: {
    opacity: 0.6,
  },
  searchButtonText: {
    color: COLORS.WHITE,
    fontSize: 16,
    fontWeight: '600',
    marginLeft: 8,
  },
  section: {
    padding: 16,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: COLORS.DARK,
    marginBottom: 16,
    textAlign: 'center',
  },
  featuresGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  featureCard: {
    width: '48%',
    backgroundColor: COLORS.WHITE,
    padding: 16,
    borderRadius: SCREEN_CONFIG.BORDER_RADIUS,
    alignItems: 'center',
    marginBottom: 12,
    ...SCREEN_CONFIG.SHADOW,
  },
  featureTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: COLORS.DARK,
    textAlign: 'center',
    marginTop: 8,
    marginBottom: 4,
  },
  featureDesc: {
    fontSize: 12,
    color: COLORS.GRAY,
    textAlign: 'center',
    lineHeight: 16,
  },
  cruiseLinesGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  cruiseLineCard: {
    width: '48%',
    backgroundColor: COLORS.WHITE,
    padding: 16,
    borderRadius: SCREEN_CONFIG.BORDER_RADIUS,
    alignItems: 'center',
    marginBottom: 12,
    borderWidth: 1,
    borderColor: COLORS.LIGHT_GRAY,
  },
  cruiseLineName: {
    fontSize: 14,
    fontWeight: '600',
    color: COLORS.PRIMARY,
    textAlign: 'center',
  },
  // Web Date Picker Styles
  webDatePicker: {
    backgroundColor: '#fff',
    padding: 20,
    borderRadius: 12,
    marginTop: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  webDatePickerTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: COLORS.PRIMARY,
    marginBottom: 15,
    textAlign: 'center',
  },
  webDateInput: {
    width: '100%',
    padding: 12,
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 8,
    fontSize: 16,
    marginBottom: 15,
  },
  webDatePickerButton: {
    backgroundColor: COLORS.GRAY,
    padding: 12,
    borderRadius: 8,
    alignItems: 'center',
  },
  webDatePickerButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
});

export default styles;
