import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F8FAFC' },
  scrollView: { flex: 1 },
  imageContainer: { position: 'relative' },
  mainImage: { width: '100%', height: 300, resizeMode: 'cover' },
  backButton: { position: 'absolute', top: 48, left: 16, width: 40, height: 40, borderRadius: 20, backgroundColor: 'rgba(0,0,0,0.5)', alignItems: 'center', justifyContent: 'center' },
  content: { padding: 16 },
  header: { marginBottom: 24 },
  titleRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 12 },
  hotelName: { fontSize: 24, fontWeight: '800', color: '#1E293B', flex: 1, marginRight: 12 },
  ratingBadge: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#FEF3C7', paddingHorizontal: 12, paddingVertical: 6, borderRadius: 20, gap: 4 },
  ratingText: { fontSize: 16, fontWeight: '700', color: '#92400E' },
  locationRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  addressText: { fontSize: 14, color: '#64748B', flex: 1 },
  section: { marginBottom: 24 },
  sectionTitle: { fontSize: 18, fontWeight: '700', color: '#1E293B', marginBottom: 12 },
  amenitiesGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 },
  amenityItem: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#FFFFFF', paddingVertical: 8, paddingHorizontal: 12, borderRadius: 8, gap: 8, shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.05, shadowRadius: 2, elevation: 1 },
  amenityText: { fontSize: 14, color: '#475569', textTransform: 'capitalize' },
  roomCard: { backgroundColor: '#FFFFFF', padding: 16, borderRadius: 12, marginBottom: 12, borderWidth: 2, borderColor: '#E2E8F0', shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.05, shadowRadius: 3, elevation: 2 },
  roomCardActive: { borderColor: '#0EA5E9', backgroundColor: '#EFF6FF' },
  roomHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 },
  roomType: { fontSize: 16, fontWeight: '700', color: '#1E293B' },
  cancellationPolicy: { fontSize: 13, color: '#64748B', marginBottom: 8 },
  roomPrice: { fontSize: 18, fontWeight: '700', color: '#0EA5E9' },
  footer: { backgroundColor: '#FFFFFF', borderTopWidth: 1, borderTopColor: '#E2E8F0', padding: 16, paddingBottom: 32, shadowColor: '#000', shadowOffset: { width: 0, height: -2 }, shadowOpacity: 0.1, shadowRadius: 4, elevation: 5 },
  totalContainer: { marginBottom: 16 },
  totalLabel: { fontSize: 14, fontWeight: '600', color: '#475569', marginBottom: 4 },
  totalAmount: { fontSize: 24, fontWeight: '700', color: '#0EA5E9' },
  bookButton: { backgroundColor: '#0EA5E9', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', paddingVertical: 16, borderRadius: 12, gap: 8, shadowColor: '#0EA5E9', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.3, shadowRadius: 8, elevation: 6 },
  bookButtonText: { fontSize: 16, fontWeight: '700', color: '#FFFFFF' },
});
