import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F8FAFC' },
  header: { flexDirection: 'row', alignItems: 'center', padding: 16, backgroundColor: '#FFFFFF', borderBottomWidth: 1, borderBottomColor: '#E2E8F0', paddingTop: 48 },
  backButton: { padding: 8, marginRight: 12 },
  headerContent: { flex: 1 },
  headerTitle: { fontSize: 18, fontWeight: '700', color: '#1E293B', marginBottom: 4 },
  headerSubtitle: { fontSize: 14, color: '#64748B' },
  sortContainer: { flexDirection: 'row', padding: 16, backgroundColor: '#FFFFFF', borderBottomWidth: 1, borderBottomColor: '#E2E8F0', gap: 8 },
  sortButton: { flex: 1, paddingVertical: 10, paddingHorizontal: 16, borderRadius: 8, backgroundColor: '#F1F5F9', alignItems: 'center' },
  sortButtonActive: { backgroundColor: '#0EA5E9' },
  sortButtonText: { fontSize: 14, fontWeight: '600', color: '#475569' },
  sortButtonTextActive: { color: '#FFFFFF' },
  resultsCount: { fontSize: 14, color: '#64748B', paddingHorizontal: 16, paddingVertical: 12 },
  scrollView: { flex: 1 },
  hotelCard: { backgroundColor: '#FFFFFF', marginHorizontal: 16, marginBottom: 12, borderRadius: 12, overflow: 'hidden', shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, shadowRadius: 4, elevation: 3 },
  hotelImage: { width: '100%', height: 180, resizeMode: 'cover' },
  ratingBadge: { position: 'absolute', top: 12, right: 12, flexDirection: 'row', alignItems: 'center', backgroundColor: 'rgba(255,255,255,0.95)', paddingHorizontal: 10, paddingVertical: 6, borderRadius: 20, gap: 4 },
  ratingText: { fontSize: 14, fontWeight: '700', color: '#1E293B' },
  hotelContent: { padding: 16 },
  hotelName: { fontSize: 18, fontWeight: '700', color: '#1E293B', marginBottom: 8 },
  locationRow: { flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: 12 },
  addressText: { fontSize: 14, color: '#64748B', flex: 1 },
  amenitiesRow: { flexDirection: 'row', gap: 12, marginBottom: 16 },
  amenityIcon: { marginRight: 4 },
  priceRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', borderTopWidth: 1, borderTopColor: '#E2E8F0', paddingTop: 16 },
  priceLabel: { fontSize: 12, color: '#64748B', marginBottom: 4 },
  priceAmount: { fontSize: 24, fontWeight: '700', color: '#0EA5E9', marginBottom: 2 },
  perNightText: { fontSize: 12, color: '#94A3B8' },
  viewButton: { backgroundColor: '#0EA5E9', paddingVertical: 12, paddingHorizontal: 24, borderRadius: 8 },
  viewButtonText: { fontSize: 15, fontWeight: '600', color: '#FFFFFF' },
  bottomPadding: { height: 20 },
});
