import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F8FAFC' },
  successContainer: { backgroundColor: '#FFFFFF', paddingTop: 60, paddingBottom: 32, alignItems: 'center', borderBottomWidth: 1, borderBottomColor: '#E2E8F0' },
  successIcon: { marginBottom: 16 },
  successTitle: { fontSize: 28, fontWeight: '800', color: '#1E293B', marginBottom: 8 },
  successSubtitle: { fontSize: 16, color: '#64748B', textAlign: 'center' },
  scrollView: { flex: 1 },
  section: { padding: 16 },
  referenceCard: { backgroundColor: '#DCFCE7', borderRadius: 12, padding: 20, alignItems: 'center', borderWidth: 2, borderColor: '#10B981' },
  referenceLabel: { fontSize: 14, fontWeight: '600', color: '#047857', marginBottom: 8 },
  referenceCode: { fontSize: 28, fontWeight: '800', color: '#065F46', letterSpacing: 1, marginBottom: 8 },
  referenceNote: { fontSize: 12, color: '#047857', textAlign: 'center' },
  sectionTitle: { fontSize: 18, fontWeight: '700', color: '#1E293B', marginBottom: 12 },
  card: { backgroundColor: '#FFFFFF', borderRadius: 12, padding: 16, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, shadowRadius: 4, elevation: 3 },
  hotelName: { fontSize: 20, fontWeight: '700', color: '#1E293B', marginBottom: 16 },
  detailRow: { flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 12 },
  detailText: { fontSize: 15, color: '#475569', flex: 1 },
  priceText: { fontSize: 18, fontWeight: '700', color: '#10B981', flex: 1 },
  guestRow: { flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 12 },
  guestName: { fontSize: 16, fontWeight: '600', color: '#1E293B' },
  guestDetail: { fontSize: 15, color: '#475569' },
  infoCard: { backgroundColor: '#FFFFFF', borderRadius: 12, padding: 16, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, shadowRadius: 4, elevation: 3 },
  infoItem: { flexDirection: 'row', alignItems: 'flex-start', gap: 12, marginBottom: 16 },
  infoText: { flex: 1, fontSize: 14, color: '#475569', lineHeight: 20 },
  footer: { backgroundColor: '#FFFFFF', borderTopWidth: 1, borderTopColor: '#E2E8F0', padding: 16, shadowColor: '#000', shadowOffset: { width: 0, height: -2 }, shadowOpacity: 0.1, shadowRadius: 4, elevation: 5 },
  doneButton: { backgroundColor: '#0EA5E9', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', paddingVertical: 16, borderRadius: 12, gap: 8, shadowColor: '#0EA5E9', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.3, shadowRadius: 8, elevation: 6 },
  doneButtonText: { fontSize: 16, fontWeight: '700', color: '#FFFFFF' },
  bottomSpace: { height: 20 },
});
